# Generated by Django 2.1.5 on 2019-01-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkybase.Account')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='inkybase.Account')),
            ],
        ),
    ]
