# Generated by Django 2.1.5 on 2019-01-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0003_auto_20190110_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reviews', to='inkybase.Account')),
                ('reviewed_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkybase.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='favoritevendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_favorited', to='inkybase.Account'),
        ),
    ]
