# Generated by Django 2.1.5 on 2019-01-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0004_auto_20190110_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('upc', models.CharField(max_length=12)),
            ],
        ),
    ]
