# Generated by Django 2.1.5 on 2019-01-10 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0005_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printerName', models.CharField(max_length=100)),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkybase.Account')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='inkybase.Printer')),
            ],
        ),
    ]
