# Generated by Django 2.1.5 on 2019-01-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0006_printeroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('pickup', models.BooleanField(default=False)),
                ('shipping', models.BooleanField(default=False)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inkybase.Account')),
            ],
        ),
        migrations.RenameModel(
            old_name='PrinterOffer',
            new_name='PrintingOffer',
        ),
        migrations.AddField(
            model_name='order',
            name='printing_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inkybase.PrintingOffer'),
        ),
    ]
