# Generated by Django 2.1.5 on 2019-01-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0008_order_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('document_types', models.ManyToManyField(to='inkybase.DocumentType')),
                ('printing_mediums', models.ManyToManyField(to='inkybase.PrintingMedium')),
                ('printing_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkybase.PrintingOffer')),
            ],
        ),
    ]
