# Generated by Django 2.1.5 on 2019-01-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0011_auto_20190112_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offerspec',
            name='document_types',
            field=models.ManyToManyField(null=True, to='inkybase.DocumentType'),
        ),
        migrations.AlterField(
            model_name='offerspec',
            name='printing_mediums',
            field=models.ManyToManyField(null=True, to='inkybase.PrintingMedium'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='printingmedium',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingoffer',
            name='maxPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printingoffer',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printingoffer',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
