# Generated by Django 2.1.5 on 2019-01-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0012_auto_20190112_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspec',
            name='document_types',
            field=models.ManyToManyField(blank=True, to='inkybase.DocumentType'),
        ),
        migrations.AlterField(
            model_name='offerspec',
            name='printing_mediums',
            field=models.ManyToManyField(blank=True, to='inkybase.PrintingMedium'),
        ),
    ]
