# Generated by Django 2.1.5 on 2019-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0013_auto_20190114_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
