# Generated by Django 2.1.5 on 2019-04-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0015_auto_20190417_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='printing_medium',
        ),
        migrations.RemoveField(
            model_name='offerspec',
            name='document_types',
        ),
        migrations.RemoveField(
            model_name='offerspec',
            name='printing_mediums',
        ),
        migrations.RemoveField(
            model_name='offerspec',
            name='printing_offer',
        ),
        migrations.RemoveField(
            model_name='printingoffer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='printingoffer',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='order',
            name='printing_offer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='OfferSpec',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='PrintingMedium',
        ),
        migrations.DeleteModel(
            name='PrintingOffer',
        ),
    ]
