# Generated by Django 2.1.5 on 2019-04-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkybase', '0016_auto_20190423_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_print', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=255)),
                ('price_per', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_info', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkybase.Account')),
            ],
        ),
    ]
